name: Deploy Hugo site to Pages

on:
  # Runs on pushes targeting the `source` branch
  push:
    branches:
      - source # 监控这个分支的推送

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write # 需要写权限来推送到 main 分支

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: source # 明确检出 source 分支
          # submodules: recursive # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0       # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest' # 或者指定一个版本 '0.119.0'
          extended: true # 如果你的主题需要 Hugo Extended 版本

      - name: Build
        run: hugo --minify # 生成的静态文件会到 public 目录

      - name: Deploy to main branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # 对于 username.github.io 仓库，必须部署到 main 或 master
          publish_branch: main # 或者 master，取决于你仓库的默认分支名
          # external_repository: TENGYan666/TENGYan666.github.io # 不需要，因为是同一仓库
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: Deploy to GitHub Pages from source branch commit ${{ github.sha }}
          # cname: your.custom.domain # 如果你使用了自定义域名